import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Categories from "../components/Categories";
import Footer from "../components/Footer";
import Intro from "../components/Intro";
import Navbar from "../components/Navbar";
import NewsLetter from "../components/NewsLetter";
import Testimonial from "../components/Testimonial";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Intro />
        <About />
        <Testimonial />
        <Categories />
        <NewsLetter />
        <Footer />
      </main>
    </div>
  );
}
